version: '3.8'

services:
  web:
    build: .
    container_name: jorgacevicdj # Drugačije ime kontejnera
    restart: always
    ports:
      - '127.0.0.1:3006:80' # Mapiramo ga na lokalni port 3001 jer je 3000 zauzet
